### ISSUE TITLE
what is "gap"?

### ISSUE THREAD

**Issue by derpyxd** [luukdv/color.js#3]
what is "gap" and why `4 * 10 /* for example */`? i want understand to make a my calculate average color function, someone can explain? 🙂
https://github.com/luukdv/color.js/blob/e739082a2d467f1e3cf8f15cfc329213407f87c5/src/color.ts#L76

**Comment by luukdv** [comment]
Hi @DerpyXD, see https://github.com/luukdv/color.js#sample. 🙂

You can use `average('img.jpg', { sample: 20 })` for example, which will interpret every 20th pixel and _skip_ the pixels in between. `gap` is an inner variable I use to determine the "gaps" between processed pixels.

Let me know if you have any other questions!
