### ISSUE TITLE
Can't find variable "document" in react native

### ISSUE THREAD

**Issue by Sheharyar566** [luukdv/color.js#6]
I'm trying to use this package for react native, but i get the error Can't find variable "document". I think it is about the document variable available in browsers. Is there a way to make it run in react native?

**Comment by luukdv** [comment]
The variable `document` is used to create a canvas element in browsers (with `document.createElement('canvas')`), but there's no equivalent in Native I think. You could try to install https://github.com/iddan/react-native-canvas and add the following (haven't tested this myself):

```js
const document = {
  createElement(type) {
    if (type === 'canvas') {
      // return the canvas from react-native-canvas
    }
  }
}
```

This doesn't seem like a good idea though. The package simply isn't made for React Native, maybe you can use something like https://github.com/osamaqarem/react-native-image-colors?

**Comment by Sheharyar566** [comment]
Thanks a lot for letting me know the possible solutions.

Yup, the react native image colors is what i am working with right now.
