### ISSUE TITLE
Extract from DOM Element

### ISSUE THREAD

**Issue by ithustle** [luukdv/color.js#7]
Hi

I'm trying to capture color from an image but return an error:

`Image loading failed at Image.img.onerror`

````
const f = document.getElementById('photoProfileFile') as HTMLImageElement;
const cc = await average(f);
```

**Comment by luukdv** [comment]
Hi @ithustle, can you provide a link to something like Codepen / Codesandbox with a minimal reproducible example?

Without it I can’t help you I’m afraid. I recommend checking out the actual error, and reading the section about CORS: https://github.com/luukdv/color.js#image-required

**Comment by ithustle** [comment]
Hi, @luukdv.

Please, find here: https://codesandbox.io/s/vibrant-cache-t6l4h?file=/src/App.js

**Comment by luukdv** [comment]
The `average` function accepts either a URL or an `<img>` element from the DOM. In your case, you're passing an `<input>` element - that won't work.

Hope that helps!
