### ISSUE TITLE
using latest tsc to get more optimized output

### ISSUE THREAD

**Issue by n-ce** [luukdv/color.js#8]
There might be a case where the latest tsc might be able to provide more optimizations.

**Comment by luukdv** [comment]
Can you clarify this a bit more? 🙂 `tsc` is currently only used for transpiling, not for the final output (for which rollup + terser are used). Also, to which target are you referring? The browser target is optimized, the CJS and ESM targets are only transpiled and compiled.

**Comment by n-ce** [comment]
I apologize for being ambigious, I noticed that the final output file was quite dated so I thought there might be place for performance improvements with newer versions of tsc.
I was refering to the browser target.
