### ISSUE TITLE
Coverage percent

### ISSUE THREAD

**Issue by acerov** [luukdv/color.js#9]
Hi,

thank you for nice library, it works as designed, but is there a way to get percentage that each color covers?

Thnx

**Comment by luukdv** [comment]
Hi @acerov,

Thanks! This is a feature request for the `prominent` function I assume? I'm not sure this would make sense to be honest. The library only interprets a small part of an image (see [sample](https://github.com/luukdv/color.js?tab=readme-ov-file#sample), which would make an exact percentage misleading.

**Comment by acerov** [comment]
Hi! Yes for  prominent function. I understand what you mean, I am actually
interested in something like rank list, from more used to lower usage
colors, the percentage for my case is not necessary.

**Comment by luukdv** [comment]
The `prominent` function already returns a ranked list, you can configure the `amount` as well.

**Comment by luukdv** [comment]
If you have any other questions, let me know!
